/*
 * Limite.java
 *
 * Created on 23 de Setembro de 2007, 17:24
 */

package testavk;

/**
 *
 * @author  wabba
 */
public class Limite extends javax.swing.JFrame {
    
    /** Creates new form Limite */
    public Limite() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        grupoTipoVK = new javax.swing.ButtonGroup();
        radioBanco = new javax.swing.JRadioButton();
        radioCalc = new javax.swing.JRadioButton();
        radioVOIP = new javax.swing.JRadioButton();
        labOutput = new javax.swing.JLabel();
        textoSaida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        virtualMultilayoutKeyboard1 = new ine5612.components.virtualkeyboard.VirtualMultilayoutKeyboard();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        grupoTipoVK.add(radioBanco);
        radioBanco.setText("Banco");
        radioBanco.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioBanco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBancoActionPerformed(evt);
            }
        });

        grupoTipoVK.add(radioCalc);
        radioCalc.setText("Calculadora");
        radioCalc.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioCalc.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCalcActionPerformed(evt);
            }
        });

        grupoTipoVK.add(radioVOIP);
        radioVOIP.setText("VOIP");
        radioVOIP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioVOIP.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioVOIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVOIPActionPerformed(evt);
            }
        });

        labOutput.setText("Sa\u00edda:");

        textoSaida.setEnabled(false);

        jLabel1.setText("Tipo do Teclado");

        virtualMultilayoutKeyboard1.setVKType(3);
        virtualMultilayoutKeyboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virtualMultilayoutKeyboard1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioBanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioCalc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioVOIP))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(virtualMultilayoutKeyboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBanco)
                    .addComponent(radioCalc)
                    .addComponent(radioVOIP))
                .addGap(44, 44, 44)
                .addComponent(virtualMultilayoutKeyboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labOutput)
                    .addComponent(textoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void virtualMultilayoutKeyboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virtualMultilayoutKeyboard1ActionPerformed
// TODO add your handling code here:
        textoSaida.setText(evt.getActionCommand());
    }//GEN-LAST:event_virtualMultilayoutKeyboard1ActionPerformed

    private void VKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VKActionPerformed
// TODO add your handling code here:
        textoSaida.setText(evt.getActionCommand());
    }//GEN-LAST:event_VKActionPerformed

    private void radioBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBancoActionPerformed
// TODO add your handling code here:
        virtualMultilayoutKeyboard1.setVKType(1);
        this.pack();
        this.repaint();
    }//GEN-LAST:event_radioBancoActionPerformed

    private void radioCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCalcActionPerformed
// TODO add your handling code here:
        virtualMultilayoutKeyboard1.setVKType(2);
        this.pack();
        this.repaint();
    }//GEN-LAST:event_radioCalcActionPerformed

    private void radioVOIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVOIPActionPerformed
// TODO add your handling code here:
        virtualMultilayoutKeyboard1.setVKType(3);
        this.pack();
        this.repaint();
    }//GEN-LAST:event_radioVOIPActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Limite().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTipoVK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labOutput;
    private javax.swing.JRadioButton radioBanco;
    private javax.swing.JRadioButton radioCalc;
    private javax.swing.JRadioButton radioVOIP;
    private javax.swing.JTextField textoSaida;
    private ine5612.components.virtualkeyboard.VirtualMultilayoutKeyboard virtualMultilayoutKeyboard1;
    // End of variables declaration//GEN-END:variables
    
}
